#pragma once
#ifndef CONFIG_HPP_
#define CONFIG_HPP_

#define APPLICATION_NAME libev_example
#define APPLICATION_CODENAME libev_example
#define APPLICATION_COPYRIGHT_YEARS 2017
#define APPLICATION_VERSION_MAJOR 0
#define APPLICATION_VERSION_MINOR 1
#define APPLICATION_VERSION_PATCH 0
#define APPLICATION_VERSION_TYPE SNAPSHOT
#define APPLICATION_VERSION_STRING 0.1.0-SNAPSHOT
#define APPLICATION_GIT_COMMIT e39b1fd2d42f7a64ec8351e3d9ddb3a32a6f5e30

#define GG_UNICODE 

#if defined GG_UNICODE == 1
#define UNICODE
#endif


#endif
